### ISSUE TITLE
Why Ping() function doesn't work?

### ISSUE THREAD

**Issue by deslum** [lib/pq#834]
I am trying to display the text of error when the database becomes inaccessible while program is running. First I launch the database container, then run a go-program. Program checks connection in the infinite loop and prints "Connected" if database available. I use Ping() function to check it. Then, while the program is running, I stop docker-container to imitate the inaccessibility of the database. But the program continues to print text "Connected". Why Ping() function doesn't return error?

go version **go1.11.5 linux/amd64**
database **postgres 9.6**

**docker-compose.yml**

```
version: '2'

services:
  db:
    image: postgres:9.6
    ports:
      - 766:5432
    environment:
      - POSTGRES_USER=notifications
      - POSTGRES_PASSWORD=12345
      - PGDATA=/var/lib/postgresql/data/pgdata

```

**main.go**

```
package main

import (
        "time"
        "fmt"
        "database/sql"
        _ "github.com/lib/pq"
)

func main() {
        db, err := sql.Open("postgres", "postgres://notifications:12345@localhost:766/notifications?sslmode=disable")
        if err != nil {
                fmt.Println(err)
                return
        }

        for {
                pingErr := db.Ping()
                if pingErr != nil {
                        fmt.Println(pingErr)
                } else {
                        fmt.Println("Connected")
                }
                time.Sleep(time.Duration(3) * time.Second)
        }
}

```

**Comment by leucos** [comment]
Hello. Using your exact example, I can not reproduce:

```
Connected
Connected
Connected
Connected
Connected
Connected
Connected # issuing `docker-compose down` here
driver: bad connection
dial tcp 127.0.0.1:766: connect: connection refused
dial tcp 127.0.0.1:766: connect: connection refused
dial tcp 127.0.0.1:766: connect: connection refused
```

Are you sure you are properly tearing down your postgres instance ? May be you had another instance running on the same port previously (and your `docker-compose up -d` never completed) ?

**Comment by dimuska139** [comment]
I've just checked this example - there is no problem already. I suppose this bug is fixed.

**Comment by fho** [comment]
@deslum I have the same issue and I can reproduce it locally.
The bug is not fixed.
I'm using lib/pq v.1.1.1.

I start a postgres instance: `docker run -p 5432:5432 postgres:latest`.
I start a program that runs `db.Ping()` every second in a loop.
I terminate the postgres docker instance.
I verify `docker ps`, ps aux and check the connection via `ss -na` to ensure postgres terminated.

`db.Ping() continues to succeed.

**Comment by mochadwi** [comment]
Any updates for this?

**Comment by fho** [comment]
@deslum sorry, I was wrong. 
Something gone wrong during the build of my test program. It used an older pq version from a vendor dir or the pkg cache and not 1.1.1.

With pq 1.1.1 `db.Ping()` works as expected.

**Comment by deslum** [comment]
Closed. Thanks for all
